version: 2
jobs:
  build:
    working_directory: ~/app/
    docker:
      - image: circleci/node:12.7.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Clone Server
          command: git clone https://github.com/Urigo/WhatsApp-Clone-Server.git --branch master-step14 --single-branch ../WhatsApp-Clone-Server
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - store_test_results:
          path: test-results
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
